version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: Documentation/User/Sphinx/requirements.txt

sphinx:
  configuration: Documentation/User/Sphinx/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub